[package]
name = "may_minihttp"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
log = "0.4"
may = "0.3"
time = "0.1"
bytes = "0.4"
httparse = "1"

[dev-dependencies]
env_logger = "0.6"
serde_json = "1"

[profile.release]
lto = true
