[package]
name = "may_minihttp"
version = "0.2.0"
edition = "2018"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
may = "0.3"
log = "0.4"
time = "0.1"
itoa = "0.4"
bytes = "0.4"
httparse = "1"
arrayvec = "0.4"

[dev-dependencies]
oorandom = "11"
num_cpus = "1.0"
env_logger = "0.7"
serde = "1"
serde_json = "1"
serde_derive = "1"
may_postgres = { git = "https://github.com/Xudong-Huang/may_postgres.git" }

[profile.release]
lto = true


[patch.crates-io]
may = { git = "https://github.com/Xudong-Huang/may.git" }
